### ISSUE TITLE
Error raising : requests.exceptions.InvalidSchema: No connection adapters were found for "[url]"

### ISSUE THREAD

**Issue by arthurteboul1** [banditelol/airscraper#3]
Hey, 
I tried to run the script. 
This error is raising : 
Error raising : requests.exceptions.InvalidSchema: No connection adapters were found for "[URL]"

Thanks for you support

**Comment by banditelol** [comment]
Just want to make sure, did you change the `[url]` part in the snippet with your airtable url ?
for example like this:
```bash
airscraper "https://airtable.com/shrSodX4SH7WDXeBS"
```

You can find detailed explanation on how to create the url from your airtable base on the [support page](https://support.airtable.com/hc/en-us/articles/205752117-Creating-a-base-share-link-or-a-view-share-link#viewsharelink)

**Comment by arthurteboul1** [comment]
Yes i did, the document is very confidential that's why I replaced it with URL

**Comment by arthurteboul1** [comment]
Tried with your url same error

**Comment by banditelol** [comment]
did you use the package from pip?
also can you tell me the details of your python version, python version manager, and your OS?

**Comment by arthurteboul1** [comment]
I started a new projet 
now the error is : 
Traceback (most recent call last):
  File "/Users/arthur/Desktop/Outils/Test_bot/main.py", line 4, in <module>
    import airscraper
  File "/Users/arthur/Desktop/Outils/Test_bot/venv/lib/python3.9/site-packages/airscraper/__init__.py", line 1, in <module>
    from .airscraper import *
  File "/Users/arthur/Desktop/Outils/Test_bot/venv/lib/python3.9/site-packages/airscraper/airscraper.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by arthurteboul1** [comment]
Python version : 3.9.7
OS : MacOs Monterrey 
How can i find my python version manager ? 
I'm still a beginner sorry for those easy questions

**Comment by banditelol** [comment]
oh, my bad
I was assuming your python environment already has `requests` package installed, so you should be fine after installing it with pip as usual
```bash
pip install requests
```

If the problem still persists, I recommend you use python version manager (I usually use `conda`, but there are many others) and try it again on python 3.6 - 3.8, currently I have only tested this package on those versions.

**Comment by banditelol** [comment]
If those solved the problem then there are 2 issues here:

- [ ] Adding documentation on supported python version
- [ ] Update `setup.py` to add `requests` package as dependency

**Comment by arthurteboul1** [comment]
I opened a jupyter notebook here is the full error : 
---------------------------------------------------------------------------
InvalidSchema                             Traceback (most recent call last)
<ipython-input-3-90b8021d569a> in <module>
      1 from airscraper import AirScraper
      2 
----> 3 client = AirScraper([url])
      4 data = client.get_table().text
      5 

/opt/anaconda3/envs/airscaper/lib/python3.6/site-packages/airscraper/airscraper.py in __init__(self, url, sess, password, locale, tz, cache)
     21         self.password = password
     22         self.page = None
---> 23         self._is_passwd_protected()
     24         if self.is_protected:
     25             self.login()

/opt/anaconda3/envs/airscaper/lib/python3.6/site-packages/airscraper/airscraper.py in _is_passwd_protected(self)
     35     def _is_passwd_protected(self) -> None:
     36         try:
---> 37             res = self.sess.get(self.url)
     38             if res.status_code == 200:
     39                 self.is_protected = "passwordProtectedShareFormContainer" in res.text

/opt/anaconda3/envs/airscaper/lib/python3.6/site-packages/requests/sessions.py in get(self, url, **kwargs)
    540 
    541         kwargs.setdefault('allow_redirects', True)
--> 542         return self.request('GET', url, **kwargs)
    543 
    544     def options(self, url, **kwargs):

/opt/anaconda3/envs/airscaper/lib/python3.6/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    527         }
    528         send_kwargs.update(settings)
--> 529         resp = self.send(prep, **send_kwargs)
    530 
    531         return resp

/opt/anaconda3/envs/airscaper/lib/python3.6/site-packages/requests/sessions.py in send(self, request, **kwargs)
    637 
    638         # Get the appropriate adapter to use
--> 639         adapter = self.get_adapter(url=request.url)
    640 
    641         # Start time (approximately) of the request

/opt/anaconda3/envs/airscaper/lib/python3.6/site-packages/requests/sessions.py in get_adapter(self, url)
    730 
    731         # Nothing matches :-/
--> 732         raise InvalidSchema("No connection adapters were found for {!r}".format(url))
    733 
    734     def close(self):

InvalidSchema: No connection adapters were found for "['https://airtable.com/shrSodX4SH7WDXeBS']"

**Comment by banditelol** [comment]
Wait, did you include square bracket around the url?
Sorry for the confusion, you should use it like this instead:
```python
From airscraper import AirScraper

url="https://your-url.here"
client = AirScraper(url)

```

**Comment by banditelol** [comment]
since there are no more activity, I'll mark it as Closed for now
